name: Visualties
favicon: null
layout_spectrum: 0.8408724623732269
typography_spectrum: 0.3193242603447288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.18122588121332228
  lightness: 0.40111887780949473
  saturation: 0.493143443018198
  rhythmicContrast: 0.1411059806123376
purpose: []
